{% set name = "hdf5storage" %}
{% set version = "0.1.19.post1" %}
{% set sha256 = null %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/frejanordsiek/hdf5storage.git
  git_rev: fb539bca9e6c13a09913f90611de5ce6633b1997

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.6
    - setuptools

  run:
    - python >=2.6
    - h5py >=2.3
    - numpy
    - scipy

test:
  imports:
    - hdf5storage

about:
  home: https://github.com/frejanordsiek/hdf5storage
  license: BSD-2-Clause
  license_file: COPYING.txt
  summary: Utilities to read/write Python types to/from HDF5 files, including MATLAB v7.3 MAT files.
  doc_url: http://pythonhosted.org/hdf5storage
  dev_url: https://github.com/frejanordsiek/hdf5storage

extra:
  recipe-maintainers:
    - jakirkham
