{% set name = "hdf5storage" %}
{% set version = "0.1.19" %}
{% set sha256 = "7a1a6badf546e8942f4d22d598aee14021796bc28918519c9687a6abb0eeef86" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.6
    - setuptools

  run:
    - python >=2.6
    - h5py >=2.3
    - numpy
    - scipy

test:
  imports:
    - hdf5storage

about:
  home: https://github.com/frejanordsiek/hdf5storage
  license: BSD-2-Clause
  license_file: COPYING.txt
  summary: Utilities to read/write Python types to/from HDF5 files, including MATLAB v7.3 MAT files.
  doc_url: http://pythonhosted.org/hdf5storage
  dev_url: https://github.com/frejanordsiek/hdf5storage

extra:
  recipe-maintainers:
    - jakirkham
