{% set name = "hdf5storage" %}
{% set version = "0.2.2" %}
{% set sha256 = "6cfd031aeba0fdfb9fb1db2aa75b09a8d6b845c98745b4a2c0c8d8d752d58fe7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.10
    - poetry-core

  run:
    - python >=3.10
    - h5py >=3.9
    - numpy
    - scipy
    - poetry

test:
  imports:
    - hdf5storage

about:
  home: http://github.com/jclds139/hdf5storage
  license: BSD-2-Clause
  license_file: COPYING.txt
  summary: Utilities to read/write Python types to/from HDF5 files, including MATLAB v7.3 MAT files.
  doc_url: http://pythonhosted.org/hdf5storage
  dev_url: http://github.com/jclds139/hdf5storage

extra:
  recipe-maintainers:
    - krono-i2
