travis:
  secure:
    BINSTAR_TOKEN: H1KKf2hqZpnV0jn+4CsSG7Q1KSjRz3wQ113Ny9AfLJsqlxGlxDahclsrzLfFiEA14cgN4fUjGtgqCkZY135ynxk2zC5X3fRIotPhLNgXUXHwiGICIuPJrnjTv2pftZhKPF0Ld11gSaxJ6ofzCPvuNeUeWeaSBcDIEp9O98EOLgyd6wvaA1UjhoP0UzHSCTcc637LaPyZuAX9C/JTadwgDU6GE9M+Ema7Y/N1QkugvyPEPHDJ1tPzwigYf9Byt44wvY+FOzysPT1ISVMbc9C4Kp1mcXhEO1lk3NFm5QCOCvvKfls9/q4BWIdT5MHMa5FZuFnbC9cuc/2+4c+/IUoWGLeCyD1K4r8Kt7W0IL1gPl2vBwzPoyYHAD7MIRHNJLdKXDOerhmEhZmxJ6f3CfMJKk9hhytHeEXiCeyJqLN8IieAt5P56UicFwdHKb0c6C1mRQ0yzv9XQfQcjrAoqtXGktkCSglsT1Bau/qqoV91ctItNgLNat22nhpj5c0haVDXRvIT54/uTbPbM3MBHo1ItnHrpPU8odNJ/Uxrjb7o/kBJYmgJJOGlOpKGGag4Mye072dquLut2/RTGYqwFa8JIgYDxDfOaow7FFefyVotOgTxOUgEojTpawJ0lXR0+10lI+fACnnpsGMMhHUGJHmB08uSzJZGXKcexm7uHWl7csU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
